package com.topit.frame.common.util;

/**
 * @ClassName: CategoryConstant
 * @Description: 分类体系常量
 * @author ivan.zhang
 * @date 2014年12月4日 下午4:45:59
 * 
 */
public class CategoryConstant {

	/**
	 * @Fields CATEGORY_TYPE_ID : 分类体系分类类型编号
	 */
	public static final int CATEGORY_TYPE_ID = 1;

	/**
	 * @Fields CATEGORY_TYPE_SQL : 查询分类体系列表树
	 */
	public static final String CATEGORY_TYPE_SQL = "(SELECT ID  AS ID ,ITEMID AS CODE ,CATEGORYNAME AS NAME ,PARENTLID  AS PARENT ,LINE AS LINE  ,'COM_OBJECT_SORT_CATEGORY' AS TABLENAME ,'icon-tree-folder' AS ICONCLS FROM COM_OBJECT_SORT_CATEGORY  WHERE SORTXTYPEID=1   )UNION ALL( SELECT A.ID AS ID,-1 AS CODE ,A.NAME AS NAME ,A.CATEGORYID AS PARENT ,A.LINE AS LINE  ,'COM_OBJECT_SORT_TYPE' AS TABLENAME ,'icon-tree-file' AS ICONCLS  FROM COM_OBJECT_SORT_TYPE  A ,COM_OBJECT_SORT_CATEGORY  B  WHERE A.CATEGORYID = B.ITEMID  AND B.SORTXTYPEID=1 ) ORDER BY LINE";
	/**
	 * @Fields MOUDLE_TYPE_ID :模块类型分类编号
	 */
	public static final int MOUDLE_TYPE_ID = 2;

	/**
	 * @Fields MOUDLE_TYPE_SQL : 查询模块列表类型
	 */
	public static final String MOUDLE_TYPE_SQL = "(SELECT ID  AS ID ,ITEMID AS CODE ,CATEGORYNAME AS NAME ,PARENTLID  AS PARENT ,LINE AS LINE  ,'COM_OBJECT_SORT_CATEGORY' AS TABLENAME ,'icon-tree-folder' AS ICONCLS FROM COM_OBJECT_SORT_CATEGORY  WHERE SORTXTYPEID=2   )UNION ALL( SELECT A.ID AS ID,-1 AS CODE ,A.NAME AS NAME ,A.CATEGORYID AS PARENT ,1 AS LINE  ,'SYS_MODULE' AS TABLENAME ,'icon-tree-file' AS ICONCLS FROM SYS_MODULE  A ,COM_OBJECT_SORT_CATEGORY  B  WHERE A.CATEGORYID = B.ITEMID  AND B.SORTXTYPEID=2 ) ORDER BY LINE";

	/**
	 * @Fields CATEGORY_TREE_SQL :查询分类类型数据
	 */
	public static final String CATEGORY_TREE_SQL = "SELECT ID, SORTXTYPEID, ITEMID, CATEGORYCODE, CATEGORYNAME, CATEGORYPINYIN, PARENTLID, LINE, LEVELNUMBER, WEBFORECOLOR, WEBBACKCOLOR, OTHEROPTION, REMARK, INACTIVE, ISSYSTEMDEFINE, CREATOR, CREATETIME, LASTEDITOR, LASTEDITTIME, VERSION   FROM  COM_OBJECT_SORT_CATEGORY  WHERE SORTXTYPEID =  ?  ORDER BY LINE";

	/** 
	* @Fields ACTION_RIGHT :查询有多少权限  有两个参数 第一个参数为 Modulepath  第二个参数为 USERID　　　　
	*/ 
	public static final String ACTION_RIGHT = "SELECT B.* FROM SYS_MODULE A ,SYS_MODULE_ACTION B , SYS_USER_USER_GROUP C , SYS_USER_GROUP_ACTION_RIGHT D  WHERE A.ID = B.MODULEID AND B.ACTIONID = D.ACTIONID AND D.GROUPID = C.GROUPID and B.MODULEID = D.MODULEID AND A.MODULEPATH = ? AND C.USERID = ?  ORDER BY B.LINE";

}
